server:
  port: 8000
spring:
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      pool:
        max-idle: ${REDIS_POOL_MAX_IDLE}
        min-idle: ${REDIS_POOL_MIN_IDLE}
        max-active: ${REDIS_POOL_MAX_ACTIVE}
        max-wait: ${REDIS_POOL_MAX_WAIT}
  application:
    name: moa-apigateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:5173, http://127.0.0.1:5173, https://localhost:5173, https://127.0.0.1:5173'
            allow-credentials: true
            allowedHeaders: '*'
            exposedHeaders: 'Accesstoken'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - PATCH
      routes:
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/istio-test/ping-with-random-delay/*
            - Method=GET
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/logout
            - Method=POST
          filters:
            - RewritePath=/users/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/signup
            - Method=POST
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/check-id
            - Method=POST
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/check-nickname
            - Method=POST
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/send-email
            - Method=POST
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/verify-code
            - Method=POST
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/reissue
            - Method=GET
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/**
          filters:
            - AuthorizationHeaderFilter
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/friends/**
          filters:
            - AuthorizationHeaderFilter
        - id: timeCapsule-service
          uri: ${TIMECAPSULE_SERVICE_URI}
          predicates:
            - Path=/time-capsules/**
          filters:
            - AuthorizationHeaderFilter
        - id: timeCapsule-service
          uri: ${TIMECAPSULE_SERVICE_URI}
          predicates:
            - Path=/time-capsules-content/**
          filters:
            - AuthorizationHeaderFilter

token:
  secret: ${TOKEN_SECRET}