server:
  port: 8000
spring:
  config:
    import: env.yml
  application:
    name: apigateway
  cloud:
    gateway:
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: 'http://localhost:5173, http://127.0.0.1:5173, https://localhost:5173, https://127.0.0.1:5173'
            allow-credentials: true
            allowedHeaders: '*'
            exposedHeaders: 'Accesstoken'
            allowedMethods:
              - PUT
              - GET
              - POST
              - DELETE
              - PATCH
      routes:
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/istio-test/ping-with-random-delay/*
            - Method=GET
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/login
            - Method=POST
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users/(?<segment>.*), /$\{segment}
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/reissue
            - Method=GET
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/**
            - Method=POST
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/users/**
          filters:
            - AuthorizationHeaderFilter
        - id: member-service
          uri: ${MEMBER_SERVICE_URI}
          predicates:
            - Path=/friends/**
          filters:
            - AuthorizationHeaderFilter
        - id: timeCapsule-service
          uri: ${TIMECAPSULE_SERVICE_URI}
          predicates:
            - Path=/time-capsules/**
          filters:
            - AuthorizationHeaderFilter

token:
  secret: ${TOKEN_SECRET}